# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'DigitalWallet-PROD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DigitalWallet
pod 'IQKeyboardManager' #iOS13 and later
pod 'Swinject' #iOS13 and later
pod 'SQLite.swift/SQLCipher', '~> 0.15.3'
pod 'lottie-ios'
pod 'ZIPFoundation', '~> 0.9'

end

post_install do |installer|
  if installer.pods_project
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
